export const countries = [
	{
		fullName: 'South Georgia',
		countryCode: 'GS',
		currency: 'SHP',
		currencyName: 'Saint Helena pound',
		currencySymbol: '£',
		flag: 'https://flagcdn.com/gs.svg',
	},
	{
		fullName: 'Grenada',
		countryCode: 'GD',
		currency: 'XCD',
		currencyName: 'Eastern Caribbean dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/gd.svg',
	},
	{
		fullName: 'Switzerland',
		countryCode: 'CH',
		currency: 'CHF',
		currencyName: 'Swiss franc',
		currencySymbol: 'Fr.',
		flag: 'https://flagcdn.com/ch.svg',
	},
	{
		fullName: 'Sierra Leone',
		countryCode: 'SL',
		currency: 'SLL',
		currencyName: 'Sierra Leonean leone',
		currencySymbol: 'Le',
		flag: 'https://flagcdn.com/sl.svg',
	},
	{
		fullName: 'Hungary',
		countryCode: 'HU',
		currency: 'HUF',
		currencyName: 'Hungarian forint',
		currencySymbol: 'Ft',
		flag: 'https://flagcdn.com/hu.svg',
	},
	{
		fullName: 'Taiwan',
		countryCode: 'TW',
		currency: 'TWD',
		currencyName: 'New Taiwan dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/tw.svg',
	},
	{
		fullName: 'Wallis and Futuna',
		countryCode: 'WF',
		currency: 'XPF',
		currencyName: 'CFP franc',
		currencySymbol: '₣',
		flag: 'https://flagcdn.com/wf.svg',
	},
	{
		fullName: 'Barbados',
		countryCode: 'BB',
		currency: 'BBD',
		currencyName: 'Barbadian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/bb.svg',
	},
	{
		fullName: 'Pitcairn Islands',
		countryCode: 'PN',
		currency: 'NZD',
		currencyName: 'New Zealand dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/pn.svg',
	},
	{
		fullName: 'Ivory Coast',
		countryCode: 'CI',
		currency: 'XOF',
		currencyName: 'West African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/ci.svg',
	},
	{
		fullName: 'Tunisia',
		countryCode: 'TN',
		currency: 'TND',
		currencyName: 'Tunisian dinar',
		currencySymbol: 'د.ت',
		flag: 'https://flagcdn.com/tn.svg',
	},
	{
		fullName: 'Italy',
		countryCode: 'IT',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/it.svg',
	},
	{
		fullName: 'Benin',
		countryCode: 'BJ',
		currency: 'XOF',
		currencyName: 'West African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/bj.svg',
	},
	{
		fullName: 'Indonesia',
		countryCode: 'ID',
		currency: 'IDR',
		currencyName: 'Indonesian rupiah',
		currencySymbol: 'Rp',
		flag: 'https://flagcdn.com/id.svg',
	},
	{
		fullName: 'Cape Verde',
		countryCode: 'CV',
		currency: 'CVE',
		currencyName: 'Cape Verdean escudo',
		currencySymbol: 'Esc',
		flag: 'https://flagcdn.com/cv.svg',
	},
	{
		fullName: 'Saint Kitts and Nevis',
		countryCode: 'KN',
		currency: 'XCD',
		currencyName: 'Eastern Caribbean dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/kn.svg',
	},
	{
		fullName: 'Laos',
		countryCode: 'LA',
		currency: 'LAK',
		currencyName: 'Lao kip',
		currencySymbol: '₭',
		flag: 'https://flagcdn.com/la.svg',
	},
	{
		fullName: 'Caribbean Netherlands',
		countryCode: 'BQ',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/bq.svg',
	},
	{
		fullName: 'Uganda',
		countryCode: 'UG',
		currency: 'UGX',
		currencyName: 'Ugandan shilling',
		currencySymbol: 'Sh',
		flag: 'https://flagcdn.com/ug.svg',
	},
	{
		fullName: 'Andorra',
		countryCode: 'AD',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/ad.svg',
	},
	{
		fullName: 'Burundi',
		countryCode: 'BI',
		currency: 'BIF',
		currencyName: 'Burundian franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/bi.svg',
	},
	{
		fullName: 'South Africa',
		countryCode: 'ZA',
		currency: 'ZAR',
		currencyName: 'South African rand',
		currencySymbol: 'R',
		flag: 'https://flagcdn.com/za.svg',
	},
	{
		fullName: 'France',
		countryCode: 'FR',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/fr.svg',
	},
	{
		fullName: 'Libya',
		countryCode: 'LY',
		currency: 'LYD',
		currencyName: 'Libyan dinar',
		currencySymbol: 'ل.د',
		flag: 'https://flagcdn.com/ly.svg',
	},
	{
		fullName: 'Mexico',
		countryCode: 'MX',
		currency: 'MXN',
		currencyName: 'Mexican peso',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/mx.svg',
	},
	{
		fullName: 'Gabon',
		countryCode: 'GA',
		currency: 'XAF',
		currencyName: 'Central African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/ga.svg',
	},
	{
		fullName: 'Northern Mariana Islands',
		countryCode: 'MP',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/mp.svg',
	},
	{
		fullName: 'North Macedonia',
		countryCode: 'MK',
		currency: 'MKD',
		currencyName: 'denar',
		currencySymbol: 'den',
		flag: 'https://flagcdn.com/mk.svg',
	},
	{
		fullName: 'China',
		countryCode: 'CN',
		currency: 'CNY',
		currencyName: 'Chinese yuan',
		currencySymbol: '¥',
		flag: 'https://flagcdn.com/cn.svg',
	},
	{
		fullName: 'Yemen',
		countryCode: 'YE',
		currency: 'YER',
		currencyName: 'Yemeni rial',
		currencySymbol: '﷼',
		flag: 'https://flagcdn.com/ye.svg',
	},
	{
		fullName: 'Saint Barthélemy',
		countryCode: 'BL',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/bl.svg',
	},
	{
		fullName: 'Guernsey',
		countryCode: 'GG',
		currency: 'GBP',
		currencyName: 'British pound',
		currencySymbol: '£',
		flag: 'https://flagcdn.com/gg.svg',
	},
	{
		fullName: 'Solomon Islands',
		countryCode: 'SB',
		currency: 'SBD',
		currencyName: 'Solomon Islands dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/sb.svg',
	},
	{
		fullName: 'Svalbard and Jan Mayen',
		countryCode: 'SJ',
		currency: 'NOK',
		currencyName: 'krone',
		currencySymbol: 'kr',
		flag: 'https://flagcdn.com/sj.svg',
	},
	{
		fullName: 'Faroe Islands',
		countryCode: 'FO',
		currency: 'DKK',
		currencyName: 'Danish krone',
		currencySymbol: 'kr',
		flag: 'https://flagcdn.com/fo.svg',
	},
	{
		fullName: 'Uzbekistan',
		countryCode: 'UZ',
		currency: 'UZS',
		currencyName: 'Uzbekistani soʻm',
		currencySymbol: "so'm",
		flag: 'https://flagcdn.com/uz.svg',
	},
	{
		fullName: 'Egypt',
		countryCode: 'EG',
		currency: 'EGP',
		currencyName: 'Egyptian pound',
		currencySymbol: '£',
		flag: 'https://flagcdn.com/eg.svg',
	},
	{
		fullName: 'Senegal',
		countryCode: 'SN',
		currency: 'XOF',
		currencyName: 'West African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/sn.svg',
	},
	{
		fullName: 'Sri Lanka',
		countryCode: 'LK',
		currency: 'LKR',
		currencyName: 'Sri Lankan rupee',
		currencySymbol: 'Rs  රු',
		flag: 'https://flagcdn.com/lk.svg',
	},
	{
		fullName: 'Palestine',
		countryCode: 'PS',
		currency: 'EGP',
		currencyName: 'Egyptian pound',
		currencySymbol: 'E£',
		flag: 'https://flagcdn.com/ps.svg',
	},
	{
		fullName: 'Bangladesh',
		countryCode: 'BD',
		currency: 'BDT',
		currencyName: 'Bangladeshi taka',
		currencySymbol: '৳',
		flag: 'https://flagcdn.com/bd.svg',
	},
	{
		fullName: 'Peru',
		countryCode: 'PE',
		currency: 'PEN',
		currencyName: 'Peruvian sol',
		currencySymbol: 'S/ ',
		flag: 'https://flagcdn.com/pe.svg',
	},
	{
		fullName: 'Singapore',
		countryCode: 'SG',
		currency: 'SGD',
		currencyName: 'Singapore dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/sg.svg',
	},
	{
		fullName: 'Turkey',
		countryCode: 'TR',
		currency: 'TRY',
		currencyName: 'Turkish lira',
		currencySymbol: '₺',
		flag: 'https://flagcdn.com/tr.svg',
	},
	{
		fullName: 'Afghanistan',
		countryCode: 'AF',
		currency: 'AFN',
		currencyName: 'Afghan afghani',
		currencySymbol: '؋',
		flag: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg',
	},
	{
		fullName: 'Aruba',
		countryCode: 'AW',
		currency: 'AWG',
		currencyName: 'Aruban florin',
		currencySymbol: 'ƒ',
		flag: 'https://flagcdn.com/aw.svg',
	},
	{
		fullName: 'Cook Islands',
		countryCode: 'CK',
		currency: 'CKD',
		currencyName: 'Cook Islands dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/ck.svg',
	},
	{
		fullName: 'United Kingdom',
		countryCode: 'GB',
		currency: 'GBP',
		currencyName: 'British pound',
		currencySymbol: '£',
		flag: 'https://flagcdn.com/gb.svg',
	},
	{
		fullName: 'Zambia',
		countryCode: 'ZM',
		currency: 'ZMW',
		currencyName: 'Zambian kwacha',
		currencySymbol: 'ZK',
		flag: 'https://flagcdn.com/zm.svg',
	},
	{
		fullName: 'Finland',
		countryCode: 'FI',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/fi.svg',
	},
	{
		fullName: 'Niger',
		countryCode: 'NE',
		currency: 'XOF',
		currencyName: 'West African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/ne.svg',
	},
	{
		fullName: 'Christmas Island',
		countryCode: 'CX',
		currency: 'AUD',
		currencyName: 'Australian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/cx.svg',
	},
	{
		fullName: 'Tokelau',
		countryCode: 'TK',
		currency: 'NZD',
		currencyName: 'New Zealand dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/tk.svg',
	},
	{
		fullName: 'Guinea-Bissau',
		countryCode: 'GW',
		currency: 'XOF',
		currencyName: 'West African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/gw.svg',
	},
	{
		fullName: 'Azerbaijan',
		countryCode: 'AZ',
		currency: 'AZN',
		currencyName: 'Azerbaijani manat',
		currencySymbol: '₼',
		flag: 'https://flagcdn.com/az.svg',
	},
	{
		fullName: 'Réunion',
		countryCode: 'RE',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/re.svg',
	},
	{
		fullName: 'Djibouti',
		countryCode: 'DJ',
		currency: 'DJF',
		currencyName: 'Djiboutian franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/dj.svg',
	},
	{
		fullName: 'North Korea',
		countryCode: 'KP',
		currency: 'KPW',
		currencyName: 'North Korean won',
		currencySymbol: '₩',
		flag: 'https://flagcdn.com/kp.svg',
	},
	{
		fullName: 'Mauritius',
		countryCode: 'MU',
		currency: 'MUR',
		currencyName: 'Mauritian rupee',
		currencySymbol: '₨',
		flag: 'https://flagcdn.com/mu.svg',
	},
	{
		fullName: 'Montserrat',
		countryCode: 'MS',
		currency: 'XCD',
		currencyName: 'Eastern Caribbean dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/ms.svg',
	},
	{
		fullName: 'United States Virgin Islands',
		countryCode: 'VI',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/vi.svg',
	},
	{
		fullName: 'Colombia',
		countryCode: 'CO',
		currency: 'COP',
		currencyName: 'Colombian peso',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/co.svg',
	},
	{
		fullName: 'Greece',
		countryCode: 'GR',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/gr.svg',
	},
	{
		fullName: 'Croatia',
		countryCode: 'HR',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/hr.svg',
	},
	{
		fullName: 'Morocco',
		countryCode: 'MA',
		currency: 'MAD',
		currencyName: 'Moroccan dirham',
		currencySymbol: 'د.م.',
		flag: 'https://flagcdn.com/ma.svg',
	},
	{
		fullName: 'Algeria',
		countryCode: 'DZ',
		currency: 'DZD',
		currencyName: 'Algerian dinar',
		currencySymbol: 'د.ج',
		flag: 'https://flagcdn.com/dz.svg',
	},
	{
		fullName: 'Antarctica',
		countryCode: 'AQ',
		currency: 'N/A',
		currencyName: 'N/A',
		currencySymbol: 'N/A',
		flag: 'https://flagcdn.com/aq.svg',
	},
	{
		fullName: 'Netherlands',
		countryCode: 'NL',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/nl.svg',
	},
	{
		fullName: 'Sudan',
		countryCode: 'SD',
		currency: 'SDG',
		currencyName: 'Sudanese pound',
		currencySymbol: 'ج.س',
		flag: 'https://flagcdn.com/sd.svg',
	},
	{
		fullName: 'Fiji',
		countryCode: 'FJ',
		currency: 'FJD',
		currencyName: 'Fijian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/fj.svg',
	},
	{
		fullName: 'Liechtenstein',
		countryCode: 'LI',
		currency: 'CHF',
		currencyName: 'Swiss franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/li.svg',
	},
	{
		fullName: 'Nepal',
		countryCode: 'NP',
		currency: 'NPR',
		currencyName: 'Nepalese rupee',
		currencySymbol: '₨',
		flag: 'https://flagcdn.com/np.svg',
	},
	{
		fullName: 'Puerto Rico',
		countryCode: 'PR',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/pr.svg',
	},
	{
		fullName: 'Georgia',
		countryCode: 'GE',
		currency: 'GEL',
		currencyName: 'lari',
		currencySymbol: '₾',
		flag: 'https://flagcdn.com/ge.svg',
	},
	{
		fullName: 'Pakistan',
		countryCode: 'PK',
		currency: 'PKR',
		currencyName: 'Pakistani rupee',
		currencySymbol: '₨',
		flag: 'https://flagcdn.com/pk.svg',
	},
	{
		fullName: 'Monaco',
		countryCode: 'MC',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/mc.svg',
	},
	{
		fullName: 'Botswana',
		countryCode: 'BW',
		currency: 'BWP',
		currencyName: 'Botswana pula',
		currencySymbol: 'P',
		flag: 'https://flagcdn.com/bw.svg',
	},
	{
		fullName: 'Lebanon',
		countryCode: 'LB',
		currency: 'LBP',
		currencyName: 'Lebanese pound',
		currencySymbol: 'ل.ل',
		flag: 'https://flagcdn.com/lb.svg',
	},
	{
		fullName: 'Papua New Guinea',
		countryCode: 'PG',
		currency: 'PGK',
		currencyName: 'Papua New Guinean kina',
		currencySymbol: 'K',
		flag: 'https://flagcdn.com/pg.svg',
	},
	{
		fullName: 'Mayotte',
		countryCode: 'YT',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/yt.svg',
	},
	{
		fullName: 'Dominican Republic',
		countryCode: 'DO',
		currency: 'DOP',
		currencyName: 'Dominican peso',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/do.svg',
	},
	{
		fullName: 'Norfolk Island',
		countryCode: 'NF',
		currency: 'AUD',
		currencyName: 'Australian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/nf.svg',
	},
	{
		fullName: 'Bouvet Island',
		countryCode: 'BV',
		currency: 'N/A',
		currencyName: 'N/A',
		currencySymbol: 'N/A',
		flag: 'https://flagcdn.com/bv.svg',
	},
	{
		fullName: 'Qatar',
		countryCode: 'QA',
		currency: 'QAR',
		currencyName: 'Qatari riyal',
		currencySymbol: 'ر.ق',
		flag: 'https://flagcdn.com/qa.svg',
	},
	{
		fullName: 'Madagascar',
		countryCode: 'MG',
		currency: 'MGA',
		currencyName: 'Malagasy ariary',
		currencySymbol: 'Ar',
		flag: 'https://flagcdn.com/mg.svg',
	},
	{
		fullName: 'India',
		countryCode: 'IN',
		currency: 'INR',
		currencyName: 'Indian rupee',
		currencySymbol: '₹',
		flag: 'https://flagcdn.com/in.svg',
	},
	{
		fullName: 'Syria',
		countryCode: 'SY',
		currency: 'SYP',
		currencyName: 'Syrian pound',
		currencySymbol: '£',
		flag: 'https://flagcdn.com/sy.svg',
	},
	{
		fullName: 'Montenegro',
		countryCode: 'ME',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/me.svg',
	},
	{
		fullName: 'Eswatini',
		countryCode: 'SZ',
		currency: 'SZL',
		currencyName: 'Swazi lilangeni',
		currencySymbol: 'L',
		flag: 'https://flagcdn.com/sz.svg',
	},
	{
		fullName: 'Paraguay',
		countryCode: 'PY',
		currency: 'PYG',
		currencyName: 'Paraguayan guaraní',
		currencySymbol: '₲',
		flag: 'https://flagcdn.com/py.svg',
	},
	{
		fullName: 'El Salvador',
		countryCode: 'SV',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/sv.svg',
	},
	{
		fullName: 'Ukraine',
		countryCode: 'UA',
		currency: 'UAH',
		currencyName: 'Ukrainian hryvnia',
		currencySymbol: '₴',
		flag: 'https://flagcdn.com/ua.svg',
	},
	{
		fullName: 'Isle of Man',
		countryCode: 'IM',
		currency: 'GBP',
		currencyName: 'British pound',
		currencySymbol: '£',
		flag: 'https://flagcdn.com/im.svg',
	},
	{
		fullName: 'Namibia',
		countryCode: 'NA',
		currency: 'NAD',
		currencyName: 'Namibian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/na.svg',
	},
	{
		fullName: 'United Arab Emirates',
		countryCode: 'AE',
		currency: 'AED',
		currencyName: 'United Arab Emirates dirham',
		currencySymbol: 'د.إ',
		flag: 'https://flagcdn.com/ae.svg',
	},
	{
		fullName: 'Bulgaria',
		countryCode: 'BG',
		currency: 'BGN',
		currencyName: 'Bulgarian lev',
		currencySymbol: 'лв',
		flag: 'https://flagcdn.com/bg.svg',
	},
	{
		fullName: 'Greenland',
		countryCode: 'GL',
		currency: 'DKK',
		currencyName: 'krone',
		currencySymbol: 'kr.',
		flag: 'https://flagcdn.com/gl.svg',
	},
	{
		fullName: 'Germany',
		countryCode: 'DE',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/de.svg',
	},
	{
		fullName: 'Cambodia',
		countryCode: 'KH',
		currency: 'KHR',
		currencyName: 'Cambodian riel',
		currencySymbol: '៛',
		flag: 'https://flagcdn.com/kh.svg',
	},
	{
		fullName: 'Iraq',
		countryCode: 'IQ',
		currency: 'IQD',
		currencyName: 'Iraqi dinar',
		currencySymbol: 'ع.د',
		flag: 'https://flagcdn.com/iq.svg',
	},
	{
		fullName: 'French Southern and Antarctic Lands',
		countryCode: 'TF',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/tf.svg',
	},
	{
		fullName: 'Sweden',
		countryCode: 'SE',
		currency: 'SEK',
		currencyName: 'Swedish krona',
		currencySymbol: 'kr',
		flag: 'https://flagcdn.com/se.svg',
	},
	{
		fullName: 'Cuba',
		countryCode: 'CU',
		currency: 'CUC',
		currencyName: 'Cuban convertible peso',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/cu.svg',
	},
	{
		fullName: 'Kyrgyzstan',
		countryCode: 'KG',
		currency: 'KGS',
		currencyName: 'Kyrgyzstani som',
		currencySymbol: 'с',
		flag: 'https://flagcdn.com/kg.svg',
	},
	{
		fullName: 'Russia',
		countryCode: 'RU',
		currency: 'RUB',
		currencyName: 'Russian ruble',
		currencySymbol: '₽',
		flag: 'https://flagcdn.com/ru.svg',
	},
	{
		fullName: 'Malaysia',
		countryCode: 'MY',
		currency: 'MYR',
		currencyName: 'Malaysian ringgit',
		currencySymbol: 'RM',
		flag: 'https://flagcdn.com/my.svg',
	},
	{
		fullName: 'São Tomé and Príncipe',
		countryCode: 'ST',
		currency: 'STN',
		currencyName: 'São Tomé and Príncipe dobra',
		currencySymbol: 'Db',
		flag: 'https://flagcdn.com/st.svg',
	},
	{
		fullName: 'Cyprus',
		countryCode: 'CY',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/cy.svg',
	},
	{
		fullName: 'Canada',
		countryCode: 'CA',
		currency: 'CAD',
		currencyName: 'Canadian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/ca.svg',
	},
	{
		fullName: 'Malawi',
		countryCode: 'MW',
		currency: 'MWK',
		currencyName: 'Malawian kwacha',
		currencySymbol: 'MK',
		flag: 'https://flagcdn.com/mw.svg',
	},
	{
		fullName: 'Saudi Arabia',
		countryCode: 'SA',
		currency: 'SAR',
		currencyName: 'Saudi riyal',
		currencySymbol: 'ر.س',
		flag: 'https://flagcdn.com/sa.svg',
	},
	{
		fullName: 'Bosnia and Herzegovina',
		countryCode: 'BA',
		currency: 'BAM',
		currencyName: 'Bosnia and Herzegovina convertible mark',
		currencySymbol: 'KM',
		flag: 'https://flagcdn.com/ba.svg',
	},
	{
		fullName: 'Ethiopia',
		countryCode: 'ET',
		currency: 'ETB',
		currencyName: 'Ethiopian birr',
		currencySymbol: 'Br',
		flag: 'https://flagcdn.com/et.svg',
	},
	{
		fullName: 'Spain',
		countryCode: 'ES',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/es.svg',
	},
	{
		fullName: 'Slovenia',
		countryCode: 'SI',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/si.svg',
	},
	{
		fullName: 'Oman',
		countryCode: 'OM',
		currency: 'OMR',
		currencyName: 'Omani rial',
		currencySymbol: 'ر.ع.',
		flag: 'https://flagcdn.com/om.svg',
	},
	{
		fullName: 'Saint Pierre and Miquelon',
		countryCode: 'PM',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/pm.svg',
	},
	{
		fullName: 'Macau',
		countryCode: 'MO',
		currency: 'MOP',
		currencyName: 'Macanese pataca',
		currencySymbol: 'P',
		flag: 'https://flagcdn.com/mo.svg',
	},
	{
		fullName: 'San Marino',
		countryCode: 'SM',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/sm.svg',
	},
	{
		fullName: 'Lesotho',
		countryCode: 'LS',
		currency: 'LSL',
		currencyName: 'Lesotho loti',
		currencySymbol: 'L',
		flag: 'https://flagcdn.com/ls.svg',
	},
	{
		fullName: 'Marshall Islands',
		countryCode: 'MH',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/mh.svg',
	},
	{
		fullName: 'Sint Maarten',
		countryCode: 'SX',
		currency: 'ANG',
		currencyName: 'Netherlands Antillean guilder',
		currencySymbol: 'ƒ',
		flag: 'https://flagcdn.com/sx.svg',
	},
	{
		fullName: 'Iceland',
		countryCode: 'IS',
		currency: 'ISK',
		currencyName: 'Icelandic króna',
		currencySymbol: 'kr',
		flag: 'https://flagcdn.com/is.svg',
	},
	{
		fullName: 'Luxembourg',
		countryCode: 'LU',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/lu.svg',
	},
	{
		fullName: 'Argentina',
		countryCode: 'AR',
		currency: 'ARS',
		currencyName: 'Argentine peso',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/ar.svg',
	},
	{
		fullName: 'Turks and Caicos Islands',
		countryCode: 'TC',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/tc.svg',
	},
	{
		fullName: 'Nauru',
		countryCode: 'NR',
		currency: 'AUD',
		currencyName: 'Australian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/nr.svg',
	},
	{
		fullName: 'Cocos (Keeling) Islands',
		countryCode: 'CC',
		currency: 'AUD',
		currencyName: 'Australian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/cc.svg',
	},
	{
		fullName: 'Western Sahara',
		countryCode: 'EH',
		currency: 'DZD',
		currencyName: 'Algerian dinar',
		currencySymbol: 'دج',
		flag: 'https://flagcdn.com/eh.svg',
	},
	{
		fullName: 'Dominica',
		countryCode: 'DM',
		currency: 'XCD',
		currencyName: 'Eastern Caribbean dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/dm.svg',
	},
	{
		fullName: 'Costa Rica',
		countryCode: 'CR',
		currency: 'CRC',
		currencyName: 'Costa Rican colón',
		currencySymbol: '₡',
		flag: 'https://flagcdn.com/cr.svg',
	},
	{
		fullName: 'Australia',
		countryCode: 'AU',
		currency: 'AUD',
		currencyName: 'Australian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/au.svg',
	},
	{
		fullName: 'Thailand',
		countryCode: 'TH',
		currency: 'THB',
		currencyName: 'Thai baht',
		currencySymbol: '฿',
		flag: 'https://flagcdn.com/th.svg',
	},
	{
		fullName: 'Haiti',
		countryCode: 'HT',
		currency: 'HTG',
		currencyName: 'Haitian gourde',
		currencySymbol: 'G',
		flag: 'https://flagcdn.com/ht.svg',
	},
	{
		fullName: 'Tuvalu',
		countryCode: 'TV',
		currency: 'AUD',
		currencyName: 'Australian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/tv.svg',
	},
	{
		fullName: 'Honduras',
		countryCode: 'HN',
		currency: 'HNL',
		currencyName: 'Honduran lempira',
		currencySymbol: 'L',
		flag: 'https://flagcdn.com/hn.svg',
	},
	{
		fullName: 'Equatorial Guinea',
		countryCode: 'GQ',
		currency: 'XAF',
		currencyName: 'Central African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/gq.svg',
	},
	{
		fullName: 'Saint Lucia',
		countryCode: 'LC',
		currency: 'XCD',
		currencyName: 'Eastern Caribbean dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/lc.svg',
	},
	{
		fullName: 'French Polynesia',
		countryCode: 'PF',
		currency: 'XPF',
		currencyName: 'CFP franc',
		currencySymbol: '₣',
		flag: 'https://flagcdn.com/pf.svg',
	},
	{
		fullName: 'Belarus',
		countryCode: 'BY',
		currency: 'BYN',
		currencyName: 'Belarusian ruble',
		currencySymbol: 'Br',
		flag: 'https://flagcdn.com/by.svg',
	},
	{
		fullName: 'Latvia',
		countryCode: 'LV',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/lv.svg',
	},
	{
		fullName: 'Palau',
		countryCode: 'PW',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/pw.svg',
	},
	{
		fullName: 'Guadeloupe',
		countryCode: 'GP',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/gp.svg',
	},
	{
		fullName: 'Philippines',
		countryCode: 'PH',
		currency: 'PHP',
		currencyName: 'Philippine peso',
		currencySymbol: '₱',
		flag: 'https://flagcdn.com/ph.svg',
	},
	{
		fullName: 'Gibraltar',
		countryCode: 'GI',
		currency: 'GIP',
		currencyName: 'Gibraltar pound',
		currencySymbol: '£',
		flag: 'https://flagcdn.com/gi.svg',
	},
	{
		fullName: 'Denmark',
		countryCode: 'DK',
		currency: 'DKK',
		currencyName: 'Danish krone',
		currencySymbol: 'kr',
		flag: 'https://flagcdn.com/dk.svg',
	},
	{
		fullName: 'Cameroon',
		countryCode: 'CM',
		currency: 'XAF',
		currencyName: 'Central African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/cm.svg',
	},
	{
		fullName: 'Guinea',
		countryCode: 'GN',
		currency: 'GNF',
		currencyName: 'Guinean franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/gn.svg',
	},
	{
		fullName: 'Bahrain',
		countryCode: 'BH',
		currency: 'BHD',
		currencyName: 'Bahraini dinar',
		currencySymbol: '.د.ب',
		flag: 'https://flagcdn.com/bh.svg',
	},
	{
		fullName: 'Suriname',
		countryCode: 'SR',
		currency: 'SRD',
		currencyName: 'Surinamese dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/sr.svg',
	},
	{
		fullName: 'DR Congo',
		countryCode: 'CD',
		currency: 'CDF',
		currencyName: 'Congolese franc',
		currencySymbol: 'FC',
		flag: 'https://flagcdn.com/cd.svg',
	},
	{
		fullName: 'Somalia',
		countryCode: 'SO',
		currency: 'SOS',
		currencyName: 'Somali shilling',
		currencySymbol: 'Sh',
		flag: 'https://flagcdn.com/so.svg',
	},
	{
		fullName: 'Czechia',
		countryCode: 'CZ',
		currency: 'CZK',
		currencyName: 'Czech koruna',
		currencySymbol: 'Kč',
		flag: 'https://flagcdn.com/cz.svg',
	},
	{
		fullName: 'New Caledonia',
		countryCode: 'NC',
		currency: 'XPF',
		currencyName: 'CFP franc',
		currencySymbol: '₣',
		flag: 'https://flagcdn.com/nc.svg',
	},
	{
		fullName: 'Vanuatu',
		countryCode: 'VU',
		currency: 'VUV',
		currencyName: 'Vanuatu vatu',
		currencySymbol: 'Vt',
		flag: 'https://flagcdn.com/vu.svg',
	},
	{
		fullName: 'Saint Helena, Ascension and Tristan da Cunha',
		countryCode: 'SH',
		currency: 'GBP',
		currencyName: 'Pound sterling',
		currencySymbol: '£',
		flag: 'https://flagcdn.com/sh.svg',
	},
	{
		fullName: 'Togo',
		countryCode: 'TG',
		currency: 'XOF',
		currencyName: 'West African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/tg.svg',
	},
	{
		fullName: 'British Virgin Islands',
		countryCode: 'VG',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/vg.svg',
	},
	{
		fullName: 'Kenya',
		countryCode: 'KE',
		currency: 'KES',
		currencyName: 'Kenyan shilling',
		currencySymbol: 'Sh',
		flag: 'https://flagcdn.com/ke.svg',
	},
	{
		fullName: 'Niue',
		countryCode: 'NU',
		currency: 'NZD',
		currencyName: 'New Zealand dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/nu.svg',
	},
	{
		fullName: 'Heard Island and McDonald Islands',
		countryCode: 'HM',
		currency: 'N/A',
		currencyName: 'N/A',
		currencySymbol: 'N/A',
		flag: 'https://flagcdn.com/hm.svg',
	},
	{
		fullName: 'Rwanda',
		countryCode: 'RW',
		currency: 'RWF',
		currencyName: 'Rwandan franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/rw.svg',
	},
	{
		fullName: 'Estonia',
		countryCode: 'EE',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/ee.svg',
	},
	{
		fullName: 'Romania',
		countryCode: 'RO',
		currency: 'RON',
		currencyName: 'Romanian leu',
		currencySymbol: 'lei',
		flag: 'https://flagcdn.com/ro.svg',
	},
	{
		fullName: 'Trinidad and Tobago',
		countryCode: 'TT',
		currency: 'TTD',
		currencyName: 'Trinidad and Tobago dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/tt.svg',
	},
	{
		fullName: 'Guyana',
		countryCode: 'GY',
		currency: 'GYD',
		currencyName: 'Guyanese dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/gy.svg',
	},
	{
		fullName: 'Timor-Leste',
		countryCode: 'TL',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/tl.svg',
	},
	{
		fullName: 'Vietnam',
		countryCode: 'VN',
		currency: 'VND',
		currencyName: 'Vietnamese đồng',
		currencySymbol: '₫',
		flag: 'https://flagcdn.com/vn.svg',
	},
	{
		fullName: 'Uruguay',
		countryCode: 'UY',
		currency: 'UYU',
		currencyName: 'Uruguayan peso',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/uy.svg',
	},
	{
		fullName: 'Vatican City',
		countryCode: 'VA',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/va.svg',
	},
	{
		fullName: 'Hong Kong',
		countryCode: 'HK',
		currency: 'HKD',
		currencyName: 'Hong Kong dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/hk.svg',
	},
	{
		fullName: 'Austria',
		countryCode: 'AT',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/at.svg',
	},
	{
		fullName: 'Antigua and Barbuda',
		countryCode: 'AG',
		currency: 'XCD',
		currencyName: 'Eastern Caribbean dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/ag.svg',
	},
	{
		fullName: 'Turkmenistan',
		countryCode: 'TM',
		currency: 'TMT',
		currencyName: 'Turkmenistan manat',
		currencySymbol: 'm',
		flag: 'https://flagcdn.com/tm.svg',
	},
	{
		fullName: 'Mozambique',
		countryCode: 'MZ',
		currency: 'MZN',
		currencyName: 'Mozambican metical',
		currencySymbol: 'MT',
		flag: 'https://flagcdn.com/mz.svg',
	},
	{
		fullName: 'Panama',
		countryCode: 'PA',
		currency: 'PAB',
		currencyName: 'Panamanian balboa',
		currencySymbol: 'B/.',
		flag: 'https://flagcdn.com/pa.svg',
	},
	{
		fullName: 'Micronesia',
		countryCode: 'FM',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/fm.svg',
	},
	{
		fullName: 'Ireland',
		countryCode: 'IE',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/ie.svg',
	},
	{
		fullName: 'Curaçao',
		countryCode: 'CW',
		currency: 'ANG',
		currencyName: 'Netherlands Antillean guilder',
		currencySymbol: 'ƒ',
		flag: 'https://flagcdn.com/cw.svg',
	},
	{
		fullName: 'French Guiana',
		countryCode: 'GF',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/gf.svg',
	},
	{
		fullName: 'Norway',
		countryCode: 'NO',
		currency: 'NOK',
		currencyName: 'Norwegian krone',
		currencySymbol: 'kr',
		flag: 'https://flagcdn.com/no.svg',
	},
	{
		fullName: 'Åland Islands',
		countryCode: 'AX',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/ax.svg',
	},
	{
		fullName: 'Central African Republic',
		countryCode: 'CF',
		currency: 'XAF',
		currencyName: 'Central African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/cf.svg',
	},
	{
		fullName: 'Burkina Faso',
		countryCode: 'BF',
		currency: 'XOF',
		currencyName: 'West African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/bf.svg',
	},
	{
		fullName: 'Eritrea',
		countryCode: 'ER',
		currency: 'ERN',
		currencyName: 'Eritrean nakfa',
		currencySymbol: 'Nfk',
		flag: 'https://flagcdn.com/er.svg',
	},
	{
		fullName: 'Tanzania',
		countryCode: 'TZ',
		currency: 'TZS',
		currencyName: 'Tanzanian shilling',
		currencySymbol: 'Sh',
		flag: 'https://flagcdn.com/tz.svg',
	},
	{
		fullName: 'South Korea',
		countryCode: 'KR',
		currency: 'KRW',
		currencyName: 'South Korean won',
		currencySymbol: '₩',
		flag: 'https://flagcdn.com/kr.svg',
	},
	{
		fullName: 'Jordan',
		countryCode: 'JO',
		currency: 'JOD',
		currencyName: 'Jordanian dinar',
		currencySymbol: 'د.ا',
		flag: 'https://flagcdn.com/jo.svg',
	},
	{
		fullName: 'Mauritania',
		countryCode: 'MR',
		currency: 'MRU',
		currencyName: 'Mauritanian ouguiya',
		currencySymbol: 'UM',
		flag: 'https://flagcdn.com/mr.svg',
	},
	{
		fullName: 'Lithuania',
		countryCode: 'LT',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/lt.svg',
	},
	{
		fullName: 'United States Minor Outlying Islands',
		countryCode: 'UM',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/um.svg',
	},
	{
		fullName: 'Slovakia',
		countryCode: 'SK',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/sk.svg',
	},
	{
		fullName: 'Angola',
		countryCode: 'AO',
		currency: 'AOA',
		currencyName: 'Angolan kwanza',
		currencySymbol: 'Kz',
		flag: 'https://flagcdn.com/ao.svg',
	},
	{
		fullName: 'Kazakhstan',
		countryCode: 'KZ',
		currency: 'KZT',
		currencyName: 'Kazakhstani tenge',
		currencySymbol: '₸',
		flag: 'https://flagcdn.com/kz.svg',
	},
	{
		fullName: 'Moldova',
		countryCode: 'MD',
		currency: 'MDL',
		currencyName: 'Moldovan leu',
		currencySymbol: 'L',
		flag: 'https://flagcdn.com/md.svg',
	},
	{
		fullName: 'Mali',
		countryCode: 'ML',
		currency: 'XOF',
		currencyName: 'West African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/ml.svg',
	},
	{
		fullName: 'Falkland Islands',
		countryCode: 'FK',
		currency: 'FKP',
		currencyName: 'Falkland Islands pound',
		currencySymbol: '£',
		flag: 'https://flagcdn.com/fk.svg',
	},
	{
		fullName: 'Armenia',
		countryCode: 'AM',
		currency: 'AMD',
		currencyName: 'Armenian dram',
		currencySymbol: '֏',
		flag: 'https://flagcdn.com/am.svg',
	},
	{
		fullName: 'Samoa',
		countryCode: 'WS',
		currency: 'WST',
		currencyName: 'Samoan tālā',
		currencySymbol: 'T',
		flag: 'https://flagcdn.com/ws.svg',
	},
	{
		fullName: 'Jersey',
		countryCode: 'JE',
		currency: 'GBP',
		currencyName: 'British pound',
		currencySymbol: '£',
		flag: 'https://flagcdn.com/je.svg',
	},
	{
		fullName: 'Japan',
		countryCode: 'JP',
		currency: 'JPY',
		currencyName: 'Japanese yen',
		currencySymbol: '¥',
		flag: 'https://flagcdn.com/jp.svg',
	},
	{
		fullName: 'Bolivia',
		countryCode: 'BO',
		currency: 'BOB',
		currencyName: 'Bolivian boliviano',
		currencySymbol: 'Bs.',
		flag: 'https://flagcdn.com/bo.svg',
	},
	{
		fullName: 'Chile',
		countryCode: 'CL',
		currency: 'CLP',
		currencyName: 'Chilean peso',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/cl.svg',
	},
	{
		fullName: 'United States',
		countryCode: 'US',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/us.svg',
	},
	{
		fullName: 'Saint Vincent and the Grenadines',
		countryCode: 'VC',
		currency: 'XCD',
		currencyName: 'Eastern Caribbean dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/vc.svg',
	},
	{
		fullName: 'Bermuda',
		countryCode: 'BM',
		currency: 'BMD',
		currencyName: 'Bermudian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/bm.svg',
	},
	{
		fullName: 'Seychelles',
		countryCode: 'SC',
		currency: 'SCR',
		currencyName: 'Seychellois rupee',
		currencySymbol: '₨',
		flag: 'https://flagcdn.com/sc.svg',
	},
	{
		fullName: 'British Indian Ocean Territory',
		countryCode: 'IO',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/io.svg',
	},
	{
		fullName: 'Guatemala',
		countryCode: 'GT',
		currency: 'GTQ',
		currencyName: 'Guatemalan quetzal',
		currencySymbol: 'Q',
		flag: 'https://flagcdn.com/gt.svg',
	},
	{
		fullName: 'Ecuador',
		countryCode: 'EC',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/ec.svg',
	},
	{
		fullName: 'Martinique',
		countryCode: 'MQ',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/mq.svg',
	},
	{
		fullName: 'Tajikistan',
		countryCode: 'TJ',
		currency: 'TJS',
		currencyName: 'Tajikistani somoni',
		currencySymbol: 'ЅМ',
		flag: 'https://flagcdn.com/tj.svg',
	},
	{
		fullName: 'Malta',
		countryCode: 'MT',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/mt.svg',
	},
	{
		fullName: 'Gambia',
		countryCode: 'GM',
		currency: 'GMD',
		currencyName: 'dalasi',
		currencySymbol: 'D',
		flag: 'https://flagcdn.com/gm.svg',
	},
	{
		fullName: 'Nigeria',
		countryCode: 'NG',
		currency: 'NGN',
		currencyName: 'Nigerian naira',
		currencySymbol: '₦',
		flag: 'https://flagcdn.com/ng.svg',
	},
	{
		fullName: 'Bahamas',
		countryCode: 'BS',
		currency: 'BSD',
		currencyName: 'Bahamian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/bs.svg',
	},
	{
		fullName: 'Kosovo',
		countryCode: 'XK',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/xk.svg',
	},
	{
		fullName: 'Kuwait',
		countryCode: 'KW',
		currency: 'KWD',
		currencyName: 'Kuwaiti dinar',
		currencySymbol: 'د.ك',
		flag: 'https://flagcdn.com/kw.svg',
	},
	{
		fullName: 'Maldives',
		countryCode: 'MV',
		currency: 'MVR',
		currencyName: 'Maldivian rufiyaa',
		currencySymbol: '.ރ',
		flag: 'https://flagcdn.com/mv.svg',
	},
	{
		fullName: 'South Sudan',
		countryCode: 'SS',
		currency: 'SSP',
		currencyName: 'South Sudanese pound',
		currencySymbol: '£',
		flag: 'https://flagcdn.com/ss.svg',
	},
	{
		fullName: 'Iran',
		countryCode: 'IR',
		currency: 'IRR',
		currencyName: 'Iranian rial',
		currencySymbol: '﷼',
		flag: 'https://flagcdn.com/ir.svg',
	},
	{
		fullName: 'Albania',
		countryCode: 'AL',
		currency: 'ALL',
		currencyName: 'Albanian lek',
		currencySymbol: 'L',
		flag: 'https://flagcdn.com/al.svg',
	},
	{
		fullName: 'Brazil',
		countryCode: 'BR',
		currency: 'BRL',
		currencyName: 'Brazilian real',
		currencySymbol: 'R$',
		flag: 'https://flagcdn.com/br.svg',
	},
	{
		fullName: 'Serbia',
		countryCode: 'RS',
		currency: 'RSD',
		currencyName: 'Serbian dinar',
		currencySymbol: 'дин.',
		flag: 'https://flagcdn.com/rs.svg',
	},
	{
		fullName: 'Belize',
		countryCode: 'BZ',
		currency: 'BZD',
		currencyName: 'Belize dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/bz.svg',
	},
	{
		fullName: 'Myanmar',
		countryCode: 'MM',
		currency: 'MMK',
		currencyName: 'Burmese kyat',
		currencySymbol: 'Ks',
		flag: 'https://flagcdn.com/mm.svg',
	},
	{
		fullName: 'Bhutan',
		countryCode: 'BT',
		currency: 'BTN',
		currencyName: 'Bhutanese ngultrum',
		currencySymbol: 'Nu.',
		flag: 'https://flagcdn.com/bt.svg',
	},
	{
		fullName: 'Venezuela',
		countryCode: 'VE',
		currency: 'VES',
		currencyName: 'Venezuelan bolívar soberano',
		currencySymbol: 'Bs.S.',
		flag: 'https://flagcdn.com/ve.svg',
	},
	{
		fullName: 'Liberia',
		countryCode: 'LR',
		currency: 'LRD',
		currencyName: 'Liberian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/lr.svg',
	},
	{
		fullName: 'Jamaica',
		countryCode: 'JM',
		currency: 'JMD',
		currencyName: 'Jamaican dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/jm.svg',
	},
	{
		fullName: 'Poland',
		countryCode: 'PL',
		currency: 'PLN',
		currencyName: 'Polish złoty',
		currencySymbol: 'zł',
		flag: 'https://flagcdn.com/pl.svg',
	},
	{
		fullName: 'Cayman Islands',
		countryCode: 'KY',
		currency: 'KYD',
		currencyName: 'Cayman Islands dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/ky.svg',
	},
	{
		fullName: 'Brunei',
		countryCode: 'BN',
		currency: 'BND',
		currencyName: 'Brunei dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/bn.svg',
	},
	{
		fullName: 'Comoros',
		countryCode: 'KM',
		currency: 'KMF',
		currencyName: 'Comorian franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/km.svg',
	},
	{
		fullName: 'Guam',
		countryCode: 'GU',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/gu.svg',
	},
	{
		fullName: 'Tonga',
		countryCode: 'TO',
		currency: 'TOP',
		currencyName: 'Tongan paʻanga',
		currencySymbol: 'T$',
		flag: 'https://flagcdn.com/to.svg',
	},
	{
		fullName: 'Kiribati',
		countryCode: 'KI',
		currency: 'AUD',
		currencyName: 'Australian dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/ki.svg',
	},
	{
		fullName: 'Ghana',
		countryCode: 'GH',
		currency: 'GHS',
		currencyName: 'Ghanaian cedi',
		currencySymbol: '₵',
		flag: 'https://flagcdn.com/gh.svg',
	},
	{
		fullName: 'Chad',
		countryCode: 'TD',
		currency: 'XAF',
		currencyName: 'Central African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/td.svg',
	},
	{
		fullName: 'Zimbabwe',
		countryCode: 'ZW',
		currency: 'ZWL',
		currencyName: 'Zimbabwean dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/zw.svg',
	},
	{
		fullName: 'Saint Martin',
		countryCode: 'MF',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/mf.svg',
	},
	{
		fullName: 'Mongolia',
		countryCode: 'MN',
		currency: 'MNT',
		currencyName: 'Mongolian tögrög',
		currencySymbol: '₮',
		flag: 'https://flagcdn.com/mn.svg',
	},
	{
		fullName: 'Portugal',
		countryCode: 'PT',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/pt.svg',
	},
	{
		fullName: 'American Samoa',
		countryCode: 'AS',
		currency: 'USD',
		currencyName: 'United States dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/as.svg',
	},
	{
		fullName: 'Republic of the Congo',
		countryCode: 'CG',
		currency: 'XAF',
		currencyName: 'Central African CFA franc',
		currencySymbol: 'Fr',
		flag: 'https://flagcdn.com/cg.svg',
	},
	{
		fullName: 'Belgium',
		countryCode: 'BE',
		currency: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		flag: 'https://flagcdn.com/be.svg',
	},
	{
		fullName: 'New Zealand',
		countryCode: 'NZ',
		currency: 'NZD',
		currencyName: 'New Zealand dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/nz.svg',
	},
	{
		fullName: 'Nicaragua',
		countryCode: 'NI',
		currency: 'NIO',
		currencyName: 'Nicaraguan córdoba',
		currencySymbol: 'C$',
		flag: 'https://flagcdn.com/ni.svg',
	},
	{
		fullName: 'Anguilla',
		countryCode: 'AI',
		currency: 'XCD',
		currencyName: 'Eastern Caribbean dollar',
		currencySymbol: '$',
		flag: 'https://flagcdn.com/ai.svg',
	},
];
