export const defaultIcons = {
	transport: 'faTrain',
	travel: 'faPlane',
	family: 'faUser',
	healthCare: 'faHeartPulse',
	groceries: 'faShoppingCart',
	gifts: 'faGift',
	sports: 'faFootballBall',
	beauty: 'faSpa',
	work: 'faBriefcase',
	other: 'faEllipsis',
	foodAndDrinks: 'faUtensils',
	salary: 'faWallet',
	businessGifts: 'faHandshake',
	extraIncome: 'faCoins',
	loan: 'faHandHoldingUsd',
	insurance: 'faShieldAlt',
	general: 'faList',
};
