services:
  # Node.js service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"  # Expose the app to the host on port 5001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
